
=head1 NAME

Faker::Plugin::JaJp::PersonFirstName - Person First Name

=cut

=head1 ABSTRACT

Person First Name for Faker

=cut

=head1 SYNOPSIS

  package main;

  use Faker::Plugin::JaJp::PersonFirstName;

  my $plugin = Faker::Plugin::JaJp::PersonFirstName->new;

  # bless(..., "Faker::Plugin::JaJp::PersonFirstName")

=cut

=head1 DESCRIPTION

This package provides methods for generating fake data for person first name.

=encoding utf8

=cut

=head1 INHERITS

This package inherits behaviors from:

L<Faker::Plugin::JaJp>

=cut

=head1 METHODS

This package provides the following methods:

=cut

=head2 execute

  execute(HashRef $data) (Str)

The execute method returns a returns a random fake person first name.

I<Since C<1.10>>

=over 4

=item execute example 1

  package main;

  use Faker::Plugin::JaJp::PersonFirstName;

  my $plugin = Faker::Plugin::JaJp::PersonFirstName->new;

  # bless(..., "Faker::Plugin::JaJp::PersonFirstName")

  # my $result = $plugin->execute;

  # '拓真';

  # my $result = $plugin->execute;

  # '智也';

  # my $result = $plugin->execute;

  # '英樹';

=back

=cut

=head2 new

  new(HashRef $data) (Plugin)

The new method returns a new instance of the class.

I<Since C<1.10>>

=over 4

=item new example 1

  package main;

  use Faker::Plugin::JaJp::PersonFirstName;

  my $plugin = Faker::Plugin::JaJp::PersonFirstName->new;

  # bless(..., "Faker::Plugin::JaJp::PersonFirstName")

=back

=cut