
=head1 NAME

Faker::Plugin::EnUs::JargonTermSuffix - Jargon Term Suffix

=cut

=head1 ABSTRACT

Jargon Term Suffix for Faker

=cut

=head1 VERSION

1.15

=cut

=head1 SYNOPSIS

  package main;

  use Faker::Plugin::EnUs::JargonTermSuffix;

  my $plugin = Faker::Plugin::EnUs::JargonTermSuffix->new;

  # bless(..., "Faker::Plugin::EnUs::JargonTermSuffix")

=cut

=head1 DESCRIPTION

This package provides methods for generating fake data for jargon term suffix.

=encoding utf8

=cut

=head1 INHERITS

This package inherits behaviors from:

L<Faker::Plugin::EnUs>

=cut

=head1 METHODS

This package provides the following methods:

=cut

=head2 execute

  execute(HashRef $data) (Str)

The execute method returns a returns a random fake jargon term suffix.

I<Since C<1.10>>

=over 4

=item execute example 1

  package main;

  use Faker::Plugin::EnUs::JargonTermSuffix;

  my $plugin = Faker::Plugin::EnUs::JargonTermSuffix->new;

  # bless(..., "Faker::Plugin::EnUs::JargonTermSuffix")

  # my $result = $plugin->execute;

  # "flexibilities";

  # my $result = $plugin->execute;

  # "graphical user interfaces";

  # my $result = $plugin->execute;

  # "standardization";

=back

=cut

=head2 new

  new(HashRef $data) (Plugin)

The new method returns a new instance of the class.

I<Since C<1.10>>

=over 4

=item new example 1

  package main;

  use Faker::Plugin::EnUs::JargonTermSuffix;

  my $plugin = Faker::Plugin::EnUs::JargonTermSuffix->new;

  # bless(..., "Faker::Plugin::EnUs::JargonTermSuffix")

=back

=cut