
=head1 NAME

Faker::Plugin::EsEs::JargonAdjective - Jargon Adjective

=cut

=head1 ABSTRACT

Jargon Adjective for Faker

=cut

=head1 VERSION

1.16

=cut

=head1 SYNOPSIS

  package main;

  use Faker::Plugin::EsEs::JargonAdjective;

  my $plugin = Faker::Plugin::EsEs::JargonAdjective->new;

  # bless(..., "Faker::Plugin::EsEs::JargonAdjective")

=cut

=head1 DESCRIPTION

This package provides methods for generating fake data for jargon adjective.

=encoding utf8

=cut

=head1 INHERITS

This package inherits behaviors from:

L<Faker::Plugin::EsEs>

=cut

=head1 METHODS

This package provides the following methods:

=cut

=head2 execute

  execute(HashRef $data) (Str)

The execute method returns a returns a random fake jargon adjective.

I<Since C<1.10>>

=over 4

=item execute example 1

  package main;

  use Faker::Plugin::EsEs::JargonAdjective;

  my $plugin = Faker::Plugin::EsEs::JargonAdjective->new;

  # bless(..., "Faker::Plugin::EsEs::JargonAdjective")

  # my $result = $plugin->execute;

  # 'virtual';

  # my $result = $plugin->execute;

  # 'killer';

  # my $result = $plugin->execute;

  # 'cutting-edge';

=back

=cut

=head2 new

  new(HashRef $data) (Plugin)

The new method returns a new instance of the class.

I<Since C<1.10>>

=over 4

=item new example 1

  package main;

  use Faker::Plugin::EsEs::JargonAdjective;

  my $plugin = Faker::Plugin::EsEs::JargonAdjective->new;

  # bless(..., "Faker::Plugin::EsEs::JargonAdjective")

=back

=cut