
=head1 NAME

Faker::Plugin::EsEs::PersonLastName - Person Last Name

=cut

=head1 ABSTRACT

Person Last Name for Faker

=cut

=head1 VERSION

1.16

=cut

=head1 SYNOPSIS

  package main;

  use Faker::Plugin::EsEs::PersonLastName;

  my $plugin = Faker::Plugin::EsEs::PersonLastName->new;

  # bless(..., "Faker::Plugin::EsEs::PersonLastName")

=cut

=head1 DESCRIPTION

This package provides methods for generating fake data for person last name.

=encoding utf8

=cut

=head1 INHERITS

This package inherits behaviors from:

L<Faker::Plugin::EsEs>

=cut

=head1 METHODS

This package provides the following methods:

=cut

=head2 execute

  execute(HashRef $data) (Str)

The execute method returns a returns a random fake person last name.

I<Since C<1.10>>

=over 4

=item execute example 1

  package main;

  use Faker::Plugin::EsEs::PersonLastName;

  my $plugin = Faker::Plugin::EsEs::PersonLastName->new;

  # bless(..., "Faker::Plugin::EsEs::PersonLastName")

  # my $result = $plugin->execute;

  # 'Expósito';

  # my $result = $plugin->execute;

  # 'Heredia';

  # my $result = $plugin->execute;

  # 'Serrato';

=back

=cut

=head2 new

  new(HashRef $data) (Plugin)

The new method returns a new instance of the class.

I<Since C<1.10>>

=over 4

=item new example 1

  package main;

  use Faker::Plugin::EsEs::PersonLastName;

  my $plugin = Faker::Plugin::EsEs::PersonLastName->new;

  # bless(..., "Faker::Plugin::EsEs::PersonLastName")

=back

=cut